### ISSUE TITLE
doesnt work since 2018-10-01 - Also, cannot sign up in forum to ask for help

### ISSUE THREAD

**Issue by welrachid** [serphacker/serposcope#203] opened 2018-10-08 09:50 UTC
Hi Guys
Sorry for putting the issue in here - im really not sure if its a bug or whatever.. but ever since oct 1st i have not been able to make a single successful run.

I dont use proxies (tried to run from home and from work).
I dont use captcha solver
i always get stuck same place (59%)
I've replaced my term with SEARCHTERMHERE in the logs below
i used to use 45-60 sec delay, now i've set up 61-90 sec. still not working past 59%

`
[2018-10-08 11:32:22,297] [Thread-20] INFO  c.s.s.t.AbstractTask - task started for module GOOGLE of day 2018-10-08 (recheck)
[2018-10-08 11:32:22,301] [Thread-20] INFO  c.s.s.t.g.GoogleTask - no captcha service configured
[2018-10-08 11:32:22,304] [Thread-20] INFO  c.s.s.t.g.GoogleTask - 17 searches to do
[2018-10-08 11:32:22,308] [Thread-20] WARN  c.s.s.t.g.GoogleTask - no proxy configured, using direct connection
[2018-10-08 11:32:22,311] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread started
[2018-10-08 11:32:22,311] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - search "SEARCHTERMHERE" | try 1 | total search done : 0/17
[2018-10-08 11:32:22,311] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - GET https://www.google.com/search?q=SEARCHTERMHERE&gl=dk&num=50 via proxy:direct try 1
[2018-10-08 11:32:22,816] [google-0] WARN  o.a.h.c.p.ResponseProcessCookies - Cookie rejected [CGIC="", version:0, domain:google.com, path:/complete/search, expiry:Tue Apr 09 02:26:58 CEST 2019] Illegal 'path' attribute "/complete/search". Path of origin: "/search"
[2018-10-08 11:32:22,817] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2018-10-08 11:32:23,208] [google-0] WARN  o.a.h.c.p.ResponseProcessCookies - Cookie rejected [CGIC="", version:0, domain:google.com, path:/complete/search, expiry:Tue Apr 09 02:26:59 CEST 2019] Illegal 'path' attribute "/complete/search". Path of origin: "/search"
[2018-10-08 11:32:23,211] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT[refetch] status=[302] exception=[none]
[2018-10-08 11:32:23,211] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
[2018-10-08 11:32:23,237] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for SEARCHTERMHERE because of ERROR_CAPTCHA_NO_SOLVER
[2018-10-08 11:32:23,237] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
[2018-10-08 11:32:23,237] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped
[2018-10-08 11:32:23,239] [Thread-20] WARN  c.s.s.t.g.GoogleTask - 1 proxies failed during the task
[2018-10-08 11:32:23,239] [Thread-20] WARN  c.s.s.t.g.GoogleTask - 17 searches have not been checked
[2018-10-08 11:32:23,239] [Thread-20] INFO  c.s.s.t.AbstractTask - task done for module GOOGLE
`

Does anyone have an idea of what i should be doing?

and if i do a manual https://www.google.com/search?q=SEARCHTERMHERE&gl=dk&num=50 i get the resultpage correctly in both chrome (logged in) and in edge 

Thanks

**Comment by noguespi** [comment] 2018-10-08 11:18
Be sure to have latest version of serposcope (2.10.0).
Your problem is your are not using captcha or proxies and you are just rate limited by Google.

**Comment by noguespi** [comment] 2018-10-08 11:18
(closing as not an issue)

**Closed by noguespi** 2018-10-08 11:18 UTC

**Comment by noguespi** [comment] 2018-10-08 11:19
By the way what is the issue to register on the forum ?

**Comment by welrachid** [comment] 2018-10-09 13:33
Hi. i actually updated and the log above is from that new version (was running 2.9 before)

@noguespi is not actually a issue - i tried to get help on the forum but was unable to sign up. I wanted to ask in the forum if the behaviour i was experiencing was a bug or not.
so instead i tried to open an issue here (because you cannot ask any questions without opening an issue), to 1) let you guys know that its not possible to signup in the forum and 2) tell you the problem im experiencing because i have no idea how to tell if its a bug or just because google is blocking your software - but not the rest of my pc.

**Comment by noguespi** [comment] 2018-10-10 14:30
> 1) let you guys know that its not possible to signup in the forum

What is the error message

**Comment by welrachid** [comment] 2018-10-10 14:54
Error
A website error has occurred. The website administrator has been notified of the issue. Sorry for the temporary inconvenience.

**Comment by noguespi** [comment] 2018-10-10 15:10
Thanks, I'm looking into the forum issue.
for 2) well it's not a bug, it's just google detect serposcope (or similar scraper), and it block/restrict it by sending captcha. There is no other solution than using multiple proxies, captcha service and increasing pause.

**Comment by welrachid** [comment] 2018-10-10 15:11
Ok thx.

**Comment by Partak** [comment] 2021-06-10 16:11
i use windows desktop version serposcope-2.13.1-x64
Continue to display this error

'path' attribute "/complete/search". Path of origin: "/search"
[2021-06-10 20:34:56,481] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT status=[302] exception=[none]
[2021-06-10 20:34:57,880] [google-0] WARN  o.a.h.c.p.ResponseProcessCookies - Cookie rejected [CGIC="", version:0, domain:google.com, path:/complete/search, expiry:Tue Dec 07 19:35:00 GMT+03:30 2021] Illegal 'path' attribute "/complete/search". Path of origin: "/search"
[2021-06-10 20:34:57,881] [google-0] INFO  c.s.s.s.g.s.GoogleScraper - GOT[refetch] status=[302] exception=[none]
[2021-06-10 20:34:57,881] [google-0] DEBUG c.s.s.s.g.s.GoogleScraper - captcha form detected via proxy:direct
[2021-06-10 20:34:58,163] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - scrap failed for طراحی سایت در اصفهان because of ERROR_CAPTCHA_NO_SOLVER
[2021-06-10 20:34:58,163] [google-0] WARN  c.s.s.t.g.GoogleTaskRunnable - no more proxy, stopping the thread
[2021-06-10 20:34:58,163] [google-0] INFO  c.s.s.t.g.GoogleTaskRunnable - google thread stopped
[2021-06-10 20:34:58,164] [Thread-20] WARN  c.s.s.t.g.GoogleTask - 1 proxies failed during the task
[2021-06-10 20:34:58,164] [Thread-20] WARN  c.s.s.t.g.GoogleTask - 6 searches have not been checked
[2021-06-10 20:34:58,164] [Thread-20] INFO  c.s.s.t.AbstractTask - task done for module GOOGLE

how to resolve this error?
